GrabTable/GrabTable

- backend/grabtable/src/main/java/edu/skku/grabtable/config/JpaAuditingConfig.java
- backend/grabtable/src/main/java/edu/skku/grabtable/controller/ReviewController.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/BaseTimeEntity.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/Cart.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/Menu.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/Order.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/Reservation.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/Review.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/ReviewStatus.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/Store.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/User.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/request/LoginRequest.java
- backend/grabtable/src/main/java/edu/skku/grabtable/domain/request/SignupRequest.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/CartRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/MenuRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/OrderRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/ReservationRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/ReviewRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/StoreRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/repository/UserRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/service/ReviewService.java
- backend/grabtable/src/test/java/edu/skku/grabtable/domain/UserTest.java
- 기능 추가
- 도메인별 JpaRepository 생성
- controller, service, request DTO 템플릿 추가
- 모든 테이블에 생성일, 수정일 칼럼 추가
> [Patch][BE] 템플릿 코드 추가

- backend/grabtable/src/main/java/edu/skku/grabtable/common/exception/GlobalExceptionHandler.java
- backend/grabtable/src/main/java/edu/skku/grabtable/reservation/controller/ReservationController.java
- backend/grabtable/src/main/java/edu/skku/grabtable/reservation/domain/request/ReservationRequest.java
- backend/grabtable/src/test/java/edu/skku/grabtable/reservation/controller/ReservationControllerTest.java
resolve #47 
- 예약 생성 오류 수정
- 일부 예외 상태코드 400 -> 404 변경
> Hotfix(be): 예외 상태코드 변경 & 예약 생성 오류 수정

- frontend/grabtable/components.json
- frontend/grabtable/package-lock.json
- frontend/grabtable/package.json
- frontend/grabtable/src/app/globals.css
- frontend/grabtable/src/app/restaurants/page.tsx
- frontend/grabtable/src/components/Inputwithbutton.tsx
- frontend/grabtable/src/components/RestaurantCard.tsx
- frontend/grabtable/src/components/ui/badge.tsx
- frontend/grabtable/src/components/ui/card.tsx
- frontend/grabtable/tailwind.config.ts
resolve #14 
- restaurantCard 컴포넌트 구현
- 해당 카드 누를 시 restaurants/[id] 로 push
- inputwithbutton import하고 filter기능 구현
> Feat(fe): 레스토랑 리스트 페이지 구현

- backend/grabtable/src/main/java/edu/skku/grabtable/auth/controller/LoginController.java
- backend/grabtable/src/main/java/edu/skku/grabtable/common/config/WebConfig.java
resolve #55 
- 이제 헤더에 credential : include 가 포함됩니다
- 쿠키의 속성에 httponly가 추가됩니다
> fix(be): CORS 에러 수정

- backend/grabtable/build.gradle
resolve #69 
- actuator 엔드포인트 활성화
- 프로메테우스 & 그라파나 설정 구축 (grabtable-monitoring 레포지토리)
> Feat(be): Spring 모니터링 구축

- infra/.gitignore
- infra/projects/grabtable/.terraform.lock.hcl
- infra/projects/grabtable/ec2_autoscaling.tf
- infra/projects/grabtable/ec2_loadbalancing.tf
- infra/projects/grabtable/ecs_cluster.tf
- infra/projects/grabtable/iam_roles.tf
- infra/projects/grabtable/launch-template/user_data.sh
- infra/projects/grabtable/main.tf
- infra/projects/grabtable/vpc_endpoints.tf
- infra/projects/grabtable/vpc_networks.tf
- infra/projects/terraform-configuration/.terraform.lock.hcl
- infra/projects/terraform-configuration/backend.tf
- infra/projects/terraform-configuration/main.tf
- vpc network, ec2 autoscaling, loadbalancing, ecs 설정 만들었습니다!
- TODO: log configuration은 설정을 안해서... role 생성하고 task definition에 해당 부분 추가해야됩니다
- TODO: rds 연결 해주어야 합니다. kakao api 연결을 위해 nat 세팅도 해줘야되고...
> Feat(infra): AWS 백엔드 환경 구축

- .gitattributes
> Chore(be): 깃허브 노출 언어 비율 오류 수정

- infra/.gitignore
- infra/projects/grabtable/ec2_loadbalancing.tf
- infra/projects/grabtable/ecs_cluster.tf
- infra/projects/grabtable/route53_routing.tf
- infra/projects/grabtable/task-definitions/task.tftpl
- ~~TODO. route table 추가해야됨..~~ 052824 완료!
- load balancer network 바꾸고
- route 53도 추가했어요
- 그외 task.json 도 없애보림
> Fix(infra): Terraform 상태 conflict 해결

- frontend/grabtable/src/app/api/login/route.ts
- frontend/grabtable/src/app/reservation/MyReservation.tsx
- frontend/grabtable/src/app/reservation/NoReservation.tsx
- frontend/grabtable/src/app/reservation/page.tsx
- frontend/grabtable/src/app/reservation/payment/page.tsx
- frontend/grabtable/src/app/restaurants/[id]/page.tsx
- frontend/grabtable/src/app/restaurants/page.tsx
- frontend/grabtable/src/components/UserCard.tsx
- frontend/grabtable/src/lib/constants.ts
resolve #80 
env 변수로 백엔드 api 연결하도록 수정했어요!
> Feat(fe): 프론트에서 백엔드 api url 변경

- .github/workflows/ci-backend.yml
- backend/grabtable/build.gradle
resolve #90 
- 이제 PR 시 Sonarqube 분석 결과를 확인할 수 있습니다.
> Feat(be): CI sonarqube 도입

- crawler/crawl.py
resolve #99 
- 크롤러 로직을 변경했습니다.
- sql 시드 데이터에 데이터를 추가했습니다.
> Feat(be): 지도뷰 마커 클릭 시 ui에 필요한 이미지, 주소 데이터 준비

- infra/projects/grabtable/task-definitions/task-definition.json
> Fix(infra): ECS 배포 오류 수정

- backend/grabtable/Dockerfile
- infra/projects/grabtable/task-definitions/task-definition.json
> Fix task definition

- frontend/grabtable/next.config.mjs
- frontend/grabtable/src/components/kakaoMap.tsx
- hotfix
- 가게 이미지 경로 config 허용
- 가게 이미지 컴포넌트 UI 개선 - 가게 이미지가 컴포넌트에 꽉 차게 보이도록 수정
> [Hotfix] 가게 이미지 패칭 

- .github/workflows/cd-no-terraform.yml
- backend/grabtable/Dockerfile
- backend/grabtable/task-definition.json
- infra/projects/grabtable/task-definitions/task-definition.json
> fix(infra): terraform 적용하지 않는 배포 액션 작성

- frontend/grabtable/src/app/api/login/route.ts
- frontend/grabtable/src/app/api/session/route.ts
- frontend/grabtable/src/app/mypage/page.tsx
> Hotfix(fe): 환경변수 오류 수정

- frontend/grabtable/next.config.mjs
- frontend/grabtable/src/app/api/login/route.ts
- frontend/grabtable/src/app/mypage/page.tsx
- frontend/grabtable/src/app/reservation/MyReservation.tsx
- frontend/grabtable/src/app/reservation/NoReservation.tsx
- frontend/grabtable/src/app/reservation/page.tsx
- frontend/grabtable/src/app/reservation/payment/page.tsx
- frontend/grabtable/src/app/restaurants/[id]/page.tsx
- frontend/grabtable/src/components/CustomAvator.tsx
- frontend/grabtable/src/components/OrderCard.tsx
- frontend/grabtable/src/components/SharedCartTable.tsx
- frontend/grabtable/src/components/UserOrderList.tsx
resolve #114 
- 마이페이지 UI 추가(유저 이름, 프로필 사진 뷰)
> Feature(fe): 마이페이지 UI 구현

- backend/grabtable/src/main/java/edu/skku/grabtable/auth/controller/LoginController.java
- samesite : Lax -> None
- domain 추가
> HotFix(be): 쿠키 옵션 변경

- backend/grabtable/src/main/java/edu/skku/grabtable/auth/controller/LoginController.java
- frontend/grabtable/next.config.mjs
- frontend/grabtable/src/app/api/login/route.ts
- frontend/grabtable/src/components/CustomAvator.tsx
- frontend/grabtable/src/lib/next-auth/session.tsx
- NextJS 세션에 저장되는 쿠키의 설정값 변경
-  local 환경에서 `sameSite: lax`
- prod 환경에서 `sameSite: None, secure: true`
> Hotfix: 쿠키 설정값 변경-2

- frontend/grabtable/src/app/api/login/route.ts
- frontend/grabtable/src/components/SharedCartTable.tsx
- frontend/grabtable/src/lib/next-auth/session.tsx
- 공동 결제 입력 금액 반영
- encrypt 상수 처리
> Hotfix(fe): 공동 결제 입력 금액 반영 및 encrypt 상수 처리

- frontend/grabtable/src/components/UserOrderList.tsx
resolve #126 
- `onClickPayment` 함수 수정했어요~
> Fix(fe): 개인 주문 결제 시도 시 금액을 정상적으로 요청 처리

- frontend/grabtable/src/app/reservation/MyReservation.tsx
> Fix(fe): 장바구니 추가 시 에러 팝업 나타나는 현상 제거

- backend/grabtable/src/main/java/edu/skku/grabtable/cart/domain/Cart.java
- backend/grabtable/src/main/java/edu/skku/grabtable/order/domain/Order.java
- backend/grabtable/src/main/java/edu/skku/grabtable/reservation/domain/Reservation.java
- backend/grabtable/src/main/java/edu/skku/grabtable/review/domain/Review.java
- backend/grabtable/src/main/java/edu/skku/grabtable/store/domain/Menu.java
- backend/grabtable/src/main/java/edu/skku/grabtable/user/domain/User.java
EAGER -> LAZY 로 변경
resolve #137
* ToOne 관계 fetch type 수정
* 기본 fetch type인 EAGER에서 LAZY로 변경
> REFACTOR(be): ToOne fetch type 변경

- backend/grabtable/src/main/java/edu/skku/grabtable/order/repository/OrderRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/reservation/repository/ReservationRepository.java
- backend/grabtable/src/main/java/edu/skku/grabtable/reservation/service/ReservationService.java
resolve #133
* Reservation 조회 쿼리  수정
* host, sharedOrder, carts fetch join으로 함께 조회
* Order 조회 쿼리 수정
* user, carts fetch join으로 함께 조회
* JPA default batch size 설정
> FEAT(be): Reservation 조회 쿼리 최적화

- README.md
(진수형 깃허브 링크도 수정)
resolve #147 
- 수정했어요~
> Docs(be): 프로젝트 설명 오류 수정

- backend/grabtable/build.gradle
- backend/grabtable/src/main/resources/db/migration/V1__init.sql
- backend/grabtable/src/main/resources/db/migration/V2__seed.sql
resolve #71 
- **JPA의 DDL 자동 생성 기능을 비활성화했습니다.**
- 우리는 flyway를 도입하여 이제 DB 스키마 변경 사항 히스토리를 형상 관리할 수 있다는 장점을 얻었지만, DDL 자동 생성의 편리함을 잃었습니다. 😭
- 앞으로 Entity에 변경사항이 발생할 시 `resources/db/migration` 경로에 다음과 같은 파일명으로 `.sql` 파일을 작성해주셔야 정상 작동을 보장합니다.
- `V{number_of_version}{underbar twice}{description}`
- e.g. 현재 `V1__init.sql`, `V2__seed.sql`이 존재하고, 다음 .sql 작성 시 `V3__next_update.sql`처럼 파일명을 작성해주셔야 합니다.
- 기존 로컬 환경의 DB와 충돌하여 서버가 실행되지 않을 수 있습니다. 이 경우 DB 컨테이너로 접속 후 다음 커맨드로 **DB를 완전히 초기화**해주세요.
```
mysql> drop database grabtable;
mysql> create database grabtable;
```
- sql 버전 관리 작업 후 서버 실행 시 flyway 관련 오류가 발생한 경우, `flyway_schema_history` 테이블의 모든 데이터를 제거해주세요.
- flyway는 sql 버전 파일을 순차적으로 실행하며 이 테이블에 checksum을 기록합니다.
- `checksum` 필드에 한번 값이 할당되면, sql 파일의 오류를 올바르게 수정한 후에도 계속해서 오류가 발생할 수 있습니다.
- 이전 버전 sql을 임의로 수정 …
> Feature(be): Flyway DB 형상 관리 툴 도입

- .github/workflows/cd-backend-k8s.yml
- .github/workflows/cd-frontend-k8s.yml
- frontend/grabtable/Dockerfile
#161 
- k8s용 먼저 추가합니다. 
- 수동으로 액션을 활성화하면 배포가 자동으로 이루어집니다.
- 일단 push기준으로 action이 활성화되는건 비활성화하고 수동으로 액션을 활성화하는 방식으로 구현하였습니다.
> feat: k8s용 CD 추가
